### ISSUE TITLE
Multiple options for backup and installation info

### ISSUE THREAD

**Issue by Lucky390163** [AbdurazaaqMohammed/APKExtractor#3]
Please add backup in apkm, apks, and xapk format, not in zip.And Please add an inbuilt installer

**Comment by AbdurazaaqMohammed** [comment]
They are all effectively archives, you can rename zip to any of them or any of them to each other. And I want to make an installer but not in this app, it doesn't really fit (It is an extractor not a manager) and I didn't try to figure out how to make installer work with root/Shizuku/Sui as yet.
